django_test/Fase1/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^vacante/$', views.vacante, name='vacante'),
	url(r'^vacaciones/$', views.vacaciones, name='vacaciones'),
	url(r'^empleado/$', views.empleado, name='empleado'),
	url(r'^hhrr/$', views.hhrr, name='hhrr'),
	url(r'^vacanteEmpleado/$', views.vacanteEmpleado, name='vacanteEmpleado'),
	url(r'^vacacionesEmpleado/$', views.vacacionesEmpleado, name='vacacionesEmpleado'),
]	

django_test/django_test/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^fase1/', include('Fase1.urls', namespace="fase1")),
]

django_test/Fase1/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import date

# Create your models here.

class Vacante(models.Model):
	cargo = models.CharField(max_length = 1024, default = "")
	vacantes = models.IntegerField(default = 0)
	TIPO_CARGO_CHOICE = (('N', 'Nuevo'), ('R', 'Reemplazo'))
	tipo_cargo = models.CharField(max_length = 1, choices = TIPO_CARGO_CHOICE, default = 'N')
	TIPO_JORNADA_CHOICE = (('P', 'Part-time'), ('F', 'Full-time'))
	tipo_jornada = models.CharField(max_length = 1, choices = TIPO_JORNADA_CHOICE, default = 'P')
	sueldo = models.FloatField(default = 0)
	comentarios = models.TextField(default = "", blank = True)
	fecha_creacion = models.DateField(default = date.today)
	solicitante = models.CharField(max_length = 1024, default = "")
	receptor = models.CharField(max_length = 1024, default = "")
	reclutador = models.CharField(max_length = 1024, default = "")
	def __str__(self):
		return "Solicitud de " + self.solicitante

class Vacaciones(models.Model):
	fecha_inicio = models.DateField(default = date.today)
	fecha_fin = models.DateField(default = date.today)
	motivo = models.TextField(default = "")
	fecha_creacion = models.DateField(default = date.today)
	solicitante = models.CharField(max_length = 1024, default = "")
	receptor = models.CharField(max_length = 1024, default = "")
	def __str__(self):
		return "Solicitud de " + self.solicitante

django_test/Fase1/forms.py
from django import forms
from .models import Vacante, Vacaciones

class VacanteForm(forms.ModelForm):
	class Meta:
		model = Vacante
		exclude = ['fecha_creacion', 'reclutador']
	def __init__(self, *args, **kwargs):
		super(VacanteForm, self).__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
			})

class VacacionesForm(forms.ModelForm):
	class Meta:
		model = Vacaciones
		exclude = ['fecha_creacion']
	def __init__(self, *args, **kwargs):
		super(VacacionesForm, self).__init__(*args, **kwargs)
		for field in iter(self.fields):
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
			})
		self.fields['fecha_inicio'].widget.attrs.update({
			'id': 'from',
			'readonly': True
		})
		self.fields['fecha_fin'].widget.attrs.update({
			'id': 'to',
			'readonly': True
		})
	def clean(self):
		cleaned_data = super(VacacionesForm, self).clean()
		start_date = cleaned_data.get("fecha_inicio")
		end_date = cleaned_data.get("fecha_fin")
		if(end_date < start_date):
			raise forms.ValidationError("Fechas invalidas!")
		return self.cleaned_data

django_test/Fase1/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, QueryDict
from .forms import VacanteForm, VacacionesForm
from .models import Vacante, Vacaciones

# Create your views here.

def home(request):
	try:
		del request.session['user']
	except KeyError:
		pass
	return render(request, 'home.html', )

def vacante(request):
	if(not request.session.get('user', False)):
		return HttpResponseRedirect('/fase1/')

	if(request.session['user'] == 'empleado'):
		error = False
		if(request.method == "POST"):
			form = VacanteForm(request.POST)
			if(form.is_valid()):
				form.save()
				return HttpResponseRedirect('/fase1/')
			else:
				error = True
		else:
			form = VacanteForm()

		context = {'form': form, 'action': "/fase1/vacante/", 'error': error, 'actionlistado': "/fase1/vacanteEmpleado/"}
		
		return render(request, 'formulario.html', context)

	else:

		if(request.method == "PUT"):
			params = QueryDict(request.body)
			v = get_object_or_404(Vacante, id=params.get('id'))
			v.reclutador = params.get('reclutador')
			v.save()
			return HttpResponse("Success")

		if(request.method == "DELETE"):
			params = QueryDict(request.body)
			v = get_object_or_404(Vacante, id=params.get('id'))
			v.delete()
			return HttpResponse("Success")

		v = Vacante.objects.all()
		context = {'solicitudes': v, 'vacante': True}
		return render(request, 'listado.html', context)

def vacaciones(request):
	if(not request.session.get('user', False)):
		return HttpResponseRedirect('/fase1/')

	if(request.session['user'] == 'empleado'):
		error = False
		if(request.method == "POST"):
			form = VacacionesForm(request.POST)
			if(form.is_valid()):
				form.save()
				return HttpResponseRedirect('/fase1/')
			else:
				error = True
		else:
			form = VacacionesForm()
		
		context = {'form': form, 'action': "/fase1/vacaciones/", 'error': error, 'actionlistado': "/fase1/vacacionesEmpleado/"}

		return render(request, 'formulario.html', context)

	else:
		if(request.method == "DELETE"):
			params = QueryDict(request.body)
			v = get_object_or_404(Vacaciones, id=params.get('id'))
			v.delete()
			return HttpResponse("Success")

		v = Vacaciones.objects.all()
		context = {'solicitudes': v, 'vacaciones': True}
		return render(request, 'listado.html', context)

def empleado(request):
	request.session['user'] = 'empleado'
	return HttpResponseRedirect('/fase1/vacante')

def hhrr(request):
	request.session['user'] = 'hhrr'
	return HttpResponseRedirect('/fase1/vacante')

def vacanteEmpleado(request):
	v = Vacante.objects.all()
	context = {'solicitudes': v, 'vacante': True}
	return render(request, 'listadoEmpleado.html', context)

def vacacionesEmpleado(request):
	v = Vacaciones.objects.all()
	context = {'solicitudes': v, 'vacaciones': True}
	return render(request, 'listadoEmpleado.html', context)

django_test/Fase1/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Fase 1</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.css' %}"/>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container header">
      <div class="navbar-header">
        <a class="logo navbar-brand" href="{% url 'fase1:home' %}">Fase 1</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li {% block vacanteActive %}{% endblock %}><a href="{% url 'fase1:vacante' %}">Vacantes</a></li>
          <li {% block vacacionesActive %}{% endblock %}><a href="{% url 'fase1:vacaciones' %}">Vacaciones</a></li>
        </ul>
      </div>
    </div>
  </nav><br><br> 

  {% block body %} {% endblock %}

  <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/functions.js' %}"></script>
</body>
</html>

django_test/Fase1/templates/formulario.html
{% extends "base.html" %}

{% block body %}

<div class="container">
	<br>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			{% if error %}
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<strong>¡Error!</strong> ¡Rellene todos los campos!
				</div>
			{% endif %}
			<form action = "{{action}}" method = "POST">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group">
					{{ field.label_tag }} {{ field }}
					</div>
				{% endfor %}
				<a href="{{actionlistado}}">
					<button type="button" class="btn btn-default pull-left">Ver todas</button>
				</a>
				<button type="submit" class="btn btn-default pull-right">Submit</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

django_test/Fase1/templates/home.html
{% extends "base.html" %}

{% block body %}

<div class="jumbotron">
  <div class="container">
    <h1>Prueba de desarrollo Django HCMFront</h1>
    <p>A continuaci&oacute;n, seleccione el tipo de usuario:</p>
  </div>
</div>

<div class="container">
  <br>
  <div class="row"></div>
	<div class="col-md-6">
		<a href="{% url 'fase1:empleado' %}">
			<button type="button" class="btn btn-default pull-right">Empleado</button>
		</a>
	</div>
	<div class="col-md-6">
		<a href="{% url 'fase1:hhrr' %}">
			<button type="button" class="btn btn-default pull-left">HHRR</button>
		</a>
	</div>
</div>

{% endblock %}

django_test/Fase1/templates/listado.html
{% extends "base.html" %}

{% block body %}

<div class="container">
  <br>
  <div class="row">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    {% for empleado in solicitudes %}
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading{{empleado.id}}">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{empleado.id}}" aria-expanded="true" aria-controls="collapse{{empleado.id}}">
            Solicitud de {{empleado.solicitante}}
            </a>
          </h4>
        </div>
        <div id="collapse{{empleado.id}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{empleado.id}}">
          <div class="panel-body">
          {% if vacante %}

            <p><b>Cargo: </b>{{empleado.cargo}}</p>
            <p><b>Vacantes: </b>{{empleado.vacantes}}</p>
            <p><b>Tipo de cargo: </b>{{empleado.get_tipo_cargo_display}}</p>
            <p><b>Tipo de jornada: </b>{{empleado.get_tipo_jornada_display}}</p>
            <p><b>Sueldo: </b>{{empleado.sueldo}}</p>
            {% if empleado.comentarios %}
              <p><b>Comentarios: </b>{{empleado.comentarios}}</p>
            {% endif %}
            <p><b>Fecha de solicitud: </b>{{empleado.fecha_creacion}}</p>
            <p><b>Solicitante: </b>{{empleado.solicitante}}</p>
            <p><b>Receptor: </b>{{empleado.receptor}}</p>

            <button type="button" class="btn btn-danger eliminar" onclick="eliminar({{empleado.id}}, '/fase1/vacante/');">Eliminar</button>
            
          {% else %}

            <p><b>Fecha de inicio: </b>{{empleado.fecha_inicio}}</p>
            <p><b>Fecha de fin: </b>{{empleado.fecha_fin}}</p>
            <p><b>Motivo: </b>{{empleado.motivo}}</p>
            <p><b>Fecha de solicitud: </b>{{empleado.fecha_creacion}}</p>
            <p><b>Solicitante: </b>{{empleado.solicitante}}</p>
            <p><b>Receptor: </b>{{empleado.receptor}}</p>

            <button type="button" class="btn btn-danger eliminar" onclick="eliminar({{empleado.id}}, '/fase1/vacaciones/');">Eliminar</button>

          {% endif %}

          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

django_test/Fase1/templates/listadoEmpleado.html
{% extends "base.html" %}

{% block body %}

<div class="container">
  <br>
  <div class="row">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    {% for empleado in solicitudes %}
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading{{empleado.id}}">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{empleado.id}}" aria-expanded="true" aria-controls="collapse{{empleado.id}}">
            Solicitud de {{empleado.solicitante}}
            </a>
          </h4>
        </div>
        <div id="collapse{{empleado.id}}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{empleado.id}}">
          <div class="panel-body">
          {% if vacante %}

            <p><b>Cargo: </b>{{empleado.cargo}}</p>
            <p><b>Vacantes: </b>{{empleado.vacantes}}</p>
            <p><b>Tipo de cargo: </b>{{empleado.get_tipo_cargo_display}}</p>
            <p><b>Tipo de jornada: </b>{{empleado.get_tipo_jornada_display}}</p>
            <p><b>Sueldo: </b>{{empleado.sueldo}}</p>
            {% if empleado.comentarios %}
              <p><b>Comentarios: </b>{{empleado.comentarios}}</p>
            {% endif %}
            <p><b>Fecha de solicitud: </b>{{empleado.fecha_creacion}}</p>
            <p><b>Solicitante: </b>{{empleado.solicitante}}</p>
            <p><b>Receptor: </b>{{empleado.receptor}}</p>

            {% if empleado.reclutador %}
              <p><b>Reclutador: </b>{{empleado.reclutador}}</p>
            {% endif %}
            
          {% else %}

            <p><b>Fecha de inicio: </b>{{empleado.fecha_inicio}}</p>
            <p><b>Fecha de fin: </b>{{empleado.fecha_fin}}</p>
            <p><b>Motivo: </b>{{empleado.motivo}}</p>
            <p><b>Fecha de solicitud: </b>{{empleado.fecha_creacion}}</p>
            <p><b>Solicitante: </b>{{empleado.solicitante}}</p>
            <p><b>Receptor: </b>{{empleado.receptor}}</p>

          {% endif %}

          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>

{% endblock %}